import { initializeApp, getApps, getApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';

/**
 * Manabu Firebase Cloud Configuration.
 * Connected to project: manabu-japanese-9007
 */
export const FIREBASE_CONFIG = {
  apiKey: 'AIzaSyA1mDgiCk5WE93SIwsBTie1wiNcQ_n_21c',
  authDomain: 'manabu-japanese-9007.firebaseapp.com',
  projectId: 'manabu-japanese-9007',
  storageBucket: 'manabu-japanese-9007.firebasestorage.app',
  messagingSenderId: '415825009519',
  appId: '1:415825009519:web:595c9bac3e810b3e2da69a',
};

/**
 * Web Client ID for Google Sign-In on Android and Web.
 * Generated by Google Cloud OAuth2 for manabu-japanese-9007.
 */
export const GOOGLE_WEB_CLIENT_ID =
  '415825009519-g73jsgq3es7q2n38tsq1oem371uhbrc8.apps.googleusercontent.com';

function initFirebaseApp(): FirebaseApp {
  if (getApps().length > 0) {
    return getApp();
  }
  return initializeApp(FIREBASE_CONFIG);
}

export const firebaseApp: FirebaseApp = initFirebaseApp();
export const firebaseAuth: Auth = getAuth(firebaseApp);
export const firebaseDb: Firestore = getFirestore(firebaseApp);
