export interface ThemePalette {
  id: string;
  name: string;
  japaneseName: string;
  description: string;
  isDark: boolean;
  colors: {
    background: string;
    surface: string;
    surfaceSubtle: string;
    surfaceHighlight: string;
    border: string;
    borderSubtle: string;
    textPrimary: string;
    textSecondary: string;
    textMuted: string;
    primary: string;
    textOnPrimary: string;
    primaryLight: string;
    primaryDark: string;
    accent: string;
    accentLight: string;
    success: string;
    successLight: string;
    error: string;
    errorLight: string;
    card: string;
    tabBar: string;
    tabBarBorder: string;
  };
}

export const THEME_PALETTES: Record<string, ThemePalette> = {
  'torii-crimson': {
    id: 'torii-crimson',
    name: 'Torii Crimson',
    japaneseName: '鳥居',
    description: 'Traditional Japanese shrine vermilion on warm washi paper',
    isDark: false,
    colors: {
      background: '#FAF8F5',
      surface: '#FFFFFF',
      surfaceSubtle: '#F4EFEA',
      surfaceHighlight: '#EFE9E1',
      border: '#E7E2DA',
      borderSubtle: '#F0EBE3',
      textPrimary: '#1F1E1D',
      textSecondary: '#6B6661',
      textMuted: '#9E9890',
      primary: '#D92D43',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#FEE2E2',
      primaryDark: '#B91C1C',
      accent: '#D97706',
      accentLight: '#FEF3C7',
      success: '#059669',
      successLight: '#D1FAE5',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      card: '#FFFFFF',
      tabBar: '#FAF8F5',
      tabBarBorder: '#E7E2DA',
    },
  },

  'midnight-tokyo': {
    id: 'midnight-tokyo',
    name: 'Midnight Tokyo',
    japaneseName: '東京夜',
    description: 'Deep OLED pitch black with vibrant neon purple accents',
    isDark: true,
    colors: {
      background: '#0D0E12',
      surface: '#15171E',
      surfaceSubtle: '#1E212B',
      surfaceHighlight: '#2A2E3D',
      border: '#2C303F',
      borderSubtle: '#20232F',
      textPrimary: '#F8FAFC',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      primary: '#A855F7',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#3B185F',
      primaryDark: '#9333EA',
      accent: '#38BDF8',
      accentLight: '#083344',
      success: '#34D399',
      successLight: '#064E3B',
      error: '#F87171',
      errorLight: '#450A0A',
      card: '#15171E',
      tabBar: '#0D0E12',
      tabBarBorder: '#20232F',
    },
  },

  'sakura-blossom': {
    id: 'sakura-blossom',
    name: 'Sakura Blossom',
    japaneseName: '桜花',
    description: 'Delicate cherry blossom petal pink on creamy morning parchment',
    isDark: false,
    colors: {
      background: '#FFF7F9',
      surface: '#FFFFFF',
      surfaceSubtle: '#FDF2F4',
      surfaceHighlight: '#FCE7EB',
      border: '#F9D5DD',
      borderSubtle: '#FCECEF',
      textPrimary: '#2D1B22',
      textSecondary: '#7A5C67',
      textMuted: '#A88D97',
      primary: '#E11D48',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#FFE4E6',
      primaryDark: '#BE123C',
      accent: '#DB2777',
      accentLight: '#FCE7F3',
      success: '#10B981',
      successLight: '#D1FAE5',
      error: '#E11D48',
      errorLight: '#FFE4E6',
      card: '#FFFFFF',
      tabBar: '#FFF7F9',
      tabBarBorder: '#F9D5DD',
    },
  },

  'matcha-zen': {
    id: 'matcha-zen',
    name: 'Matcha Zen',
    japaneseName: '宇治抹茶',
    description: 'Earthy Uji tea ceremonies and calming bamboo groves',
    isDark: false,
    colors: {
      background: '#F5F7F4',
      surface: '#FFFFFF',
      surfaceSubtle: '#ECF1EC',
      surfaceHighlight: '#E0E9E0',
      border: '#D1DDD1',
      borderSubtle: '#E2EBE2',
      textPrimary: '#1A241A',
      textSecondary: '#4A5B4A',
      textMuted: '#849684',
      primary: '#15803D',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#DCFCE7',
      primaryDark: '#166534',
      accent: '#B45309',
      accentLight: '#FEF3C7',
      success: '#15803D',
      successLight: '#DCFCE7',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      card: '#FFFFFF',
      tabBar: '#F5F7F4',
      tabBarBorder: '#D1DDD1',
    },
  },

  'cyberpunk-neo': {
    id: 'cyberpunk-neo',
    name: 'Cyberpunk Neo',
    japaneseName: '電脳都市',
    description: 'High-voltage neon cyan and electric magenta on dark grid',
    isDark: true,
    colors: {
      background: '#090D16',
      surface: '#111827',
      surfaceSubtle: '#1F2937',
      surfaceHighlight: '#374151',
      border: '#374151',
      borderSubtle: '#1F2937',
      textPrimary: '#00F0FF',
      textSecondary: '#E2E8F0',
      textMuted: '#94A3B8',
      primary: '#06B6D4',
      textOnPrimary: '#000000',
      primaryLight: '#164E63',
      primaryDark: '#0891B2',
      accent: '#F43F5E',
      accentLight: '#4C0519',
      success: '#10B981',
      successLight: '#064E3B',
      error: '#F43F5E',
      errorLight: '#4C0519',
      card: '#111827',
      tabBar: '#090D16',
      tabBarBorder: '#1F2937',
    },
  },

  'kyoto-sunset': {
    id: 'kyoto-sunset',
    name: 'Kyoto Sunset',
    japaneseName: '夕暮れ京都',
    description: 'Golden hour terracotta orange, roasted tea, and dusk charcoal',
    isDark: true,
    colors: {
      background: '#18151B',
      surface: '#221E27',
      surfaceSubtle: '#2E2935',
      surfaceHighlight: '#3E3747',
      border: '#413A4B',
      borderSubtle: '#2B2633',
      textPrimary: '#FFF1EE',
      textSecondary: '#D1C4BF',
      textMuted: '#9A8E89',
      primary: '#F97316',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#4A1D05',
      primaryDark: '#EA580C',
      accent: '#FBBF24',
      accentLight: '#451A03',
      success: '#34D399',
      successLight: '#064E3B',
      error: '#EF4444',
      errorLight: '#450A0A',
      card: '#221E27',
      tabBar: '#18151B',
      tabBarBorder: '#2B2633',
    },
  },

  'fuji-snow': {
    id: 'fuji-snow',
    name: 'Fuji Snow',
    japaneseName: '富士雪景',
    description: 'Glacial winter skies, frosted alpine peaks, and crisp ice blue',
    isDark: false,
    colors: {
      background: '#F0F7FA',
      surface: '#FFFFFF',
      surfaceSubtle: '#E4EFF5',
      surfaceHighlight: '#D5E6F0',
      border: '#C0D8E6',
      borderSubtle: '#D9E9F2',
      textPrimary: '#0F1E2A',
      textSecondary: '#415B6E',
      textMuted: '#7E9BB0',
      primary: '#0284C7',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#E0F2FE',
      primaryDark: '#0369A1',
      accent: '#0D9488',
      accentLight: '#CCFBF1',
      success: '#059669',
      successLight: '#D1FAE5',
      error: '#DC2626',
      errorLight: '#FEE2E2',
      card: '#FFFFFF',
      tabBar: '#F0F7FA',
      tabBarBorder: '#C0D8E6',
    },
  },

  'sapphire-bloom': {
    id: 'sapphire-bloom',
    name: 'Sapphire Bloom',
    japaneseName: '青藍',
    description: 'Royal indigo depths with sparkling sapphire highlights',
    isDark: true,
    colors: {
      background: '#0B1120',
      surface: '#121A2F',
      surfaceSubtle: '#1C2744',
      surfaceHighlight: '#29375E',
      border: '#2E3E6A',
      borderSubtle: '#192440',
      textPrimary: '#F1F5F9',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      primary: '#6366F1',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#1E1B4B',
      primaryDark: '#4F46E5',
      accent: '#38BDF8',
      accentLight: '#082F49',
      success: '#10B981',
      successLight: '#064E3B',
      error: '#F43F5E',
      errorLight: '#4C0519',
      card: '#121A2F',
      tabBar: '#0B1120',
      tabBarBorder: '#192440',
    },
  },

  'amethyst-mist': {
    id: 'amethyst-mist',
    name: 'Amethyst Mist',
    japaneseName: '紫苑',
    description: 'Enchanting imperial violet mist and twilight lavender',
    isDark: true,
    colors: {
      background: '#15131C',
      surface: '#1D1A27',
      surfaceSubtle: '#292537',
      surfaceHighlight: '#3B354F',
      border: '#3E3754',
      borderSubtle: '#242031',
      textPrimary: '#FAF5FF',
      textSecondary: '#C084FC',
      textMuted: '#8B5CF6',
      primary: '#A855F7',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#3B0764',
      primaryDark: '#9333EA',
      accent: '#EC4899',
      accentLight: '#500724',
      success: '#34D399',
      successLight: '#064E3B',
      error: '#FB7185',
      errorLight: '#4C0519',
      card: '#1D1A27',
      tabBar: '#15131C',
      tabBarBorder: '#242031',
    },
  },

  'monkeytype-charcoal': {
    id: 'monkeytype-charcoal',
    name: 'Charcoal Gold',
    japaneseName: '墨炭',
    description: 'Minimalist typing slate with glowing canary gold accents',
    isDark: true,
    colors: {
      background: '#24262A',
      surface: '#2C2E33',
      surfaceSubtle: '#363940',
      surfaceHighlight: '#434750',
      border: '#454852',
      borderSubtle: '#30333A',
      textPrimary: '#E2B714',
      textSecondary: '#D1D0C5',
      textMuted: '#646669',
      primary: '#E2B714',
      textOnPrimary: '#24262A',
      primaryLight: '#3E3411',
      primaryDark: '#CA8A04',
      accent: '#646669',
      accentLight: '#2C2E33',
      success: '#4ADE80',
      successLight: '#14532D',
      error: '#CA4754',
      errorLight: '#450A0A',
      card: '#2C2E33',
      tabBar: '#24262A',
      tabBarBorder: '#30333A',
    },
  },

  'paper-and-ink': {
    id: 'paper-and-ink',
    name: 'Paper & Ink',
    japaneseName: '和紙墨筆',
    description: 'Warm vintage calligraphy washi with rich sumi ink',
    isDark: false,
    colors: {
      background: '#F9F6F0',
      surface: '#FFFFFF',
      surfaceSubtle: '#F0EBE1',
      surfaceHighlight: '#E7E0D3',
      border: '#DACFC0',
      borderSubtle: '#EAE3D6',
      textPrimary: '#292524',
      textSecondary: '#57534E',
      textMuted: '#8C857B',
      primary: '#854D0E',
      textOnPrimary: '#FFFFFF',
      primaryLight: '#FEF3C7',
      primaryDark: '#713F12',
      accent: '#B45309',
      accentLight: '#FFEDD5',
      success: '#15803D',
      successLight: '#DCFCE7',
      error: '#B91C1C',
      errorLight: '#FEE2E2',
      card: '#FFFFFF',
      tabBar: '#F9F6F0',
      tabBarBorder: '#DACFC0',
    },
  },

  'shinobi-stealth': {
    id: 'shinobi-stealth',
    name: 'Shinobi Stealth',
    japaneseName: '忍',
    description: 'Absolute OLED darkness with titanium stealth contrast',
    isDark: true,
    colors: {
      background: '#000000',
      surface: '#111111',
      surfaceSubtle: '#1C1C1C',
      surfaceHighlight: '#2A2A2A',
      border: '#2E2E2E',
      borderSubtle: '#1F1F1F',
      textPrimary: '#FFFFFF',
      textSecondary: '#9E9E9E',
      textMuted: '#616161',
      primary: '#FFFFFF',
      textOnPrimary: '#000000',
      primaryLight: '#262626',
      primaryDark: '#E0E0E0',
      accent: '#757575',
      accentLight: '#212121',
      success: '#4ADE80',
      successLight: '#14532D',
      error: '#F87171',
      errorLight: '#450A0A',
      card: '#111111',
      tabBar: '#000000',
      tabBarBorder: '#1F1F1F',
    },
  },

  'bunpro-dark': {
    id: 'bunpro-dark',
    name: 'Bunpro Dark Learning',
    japaneseName: '文法道場',
    description: 'Authentic Bunpro/Stitch deep learning indigo with tatami borders and warm crimson',
    isDark: true,
    colors: {
      background: '#00161E',
      surface: '#04232D',
      surfaceSubtle: '#0F3947',
      surfaceHighlight: '#1A5163',
      border: '#12333E',
      borderSubtle: '#17424F',
      textPrimary: '#F0F0F0',
      textSecondary: '#8FA2AA',
      textMuted: '#5C727D',
      primary: '#FFB3AF',
      textOnPrimary: '#68000E',
      primaryLight: '#2D1B22',
      primaryDark: '#C74A4A',
      accent: '#F9BD22',
      accentLight: '#2A2415',
      success: '#34D399',
      successLight: '#063B28',
      error: '#FFB4AB',
      errorLight: '#450A0A',
      card: '#04232D',
      tabBar: '#00161E',
      tabBarBorder: '#12333E',
    },
  },
};

export const DEFAULT_THEME_ID = 'torii-crimson';

export function getThemePalette(id: string): ThemePalette {
  return THEME_PALETTES[id] || THEME_PALETTES[DEFAULT_THEME_ID];
}
